version: '2'

volumes:
  mongo_data: {}
  elastic_data: {}
  postgres_data: {}

services:

  #sdk:
    #build:
      #context: ../../5GCity-SDK-Front-End-GUI/

  #generator:
  #  depends_on:
  #    - redis
  #    - generator_db
  #  build:
  #    context: ../../MetricGenerator/
  #redis:
  #  image: "redis:latest"
  #generator_db:
  #  image: postgres
  #  environment:
  #    - POSTGRES_DB=generator
  #    - POSTGRES_USER=generator
  #    - POSTGRES_PASSWORD=generator

  dashboard:
    build:
      context: ../../5GCity-Dashboard-new/
      args:
        - API_BASE_URL=https://5gcity-dashboard.i2cat.net/gw/slicemanagerapi
        - AUTH_SERVER_URL=https://5gcity-dashboard.i2cat.net/auth

  # --------------------
  # Auxiliary Services
  # --------------------
  nginx-service:
    image: nginx
    volumes:
      - /home/centos/5GCity-AAA/aaa_compose/nginx/nginx.conf:/etc/nginx/conf.d/aaa.conf
      - /home/centos/5GCity-AAA/aaa_compose/nginx/certs:/etc/nginx/ssl/cert/
    ports:
      - 443:443
      - 80:80
    extra_hosts:
      - "5gcity-dashboard.i2cat.net:192.168.111.234"

  postgresdb:
    hostname: postgresql
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    hostname: aaaelasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536

  mongodb:
    hostname: aaamongodb
    image: mongo:3.4
    volumes:
      - mongo_data:/data/db

  # --------------------
  # GRAVITEE Services
  # --------------------

  gravitee_gateway:
    image: graviteeio/gateway:1.21.3
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/gateway:/etc/gravitee.io/log
      - ./scripts/gateway:/etc/gravitee.io/scripts
    environment:
      - GRAVITEE_HTTP_PORT=8000
      - GRAVITEE_MANAGEMENT_MONGODB_URI=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - GRAVITEE_REPORTERS_ELASTICSEARCH_ENDPOINTS_0=http://elasticsearch:9200
    extra_hosts:
      - "5gcity-dashboard.i2cat.net:192.168.111.234"

  management_api:
    image: graviteeio/management-api:1.21.3
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/management-api:/home/gravitee/logs
    environment:
      - GRAVITEE_MANAGEMENT_MONGODB_URI=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - GRAVITEE_ANALYTICS_ELASTICSEARCH_ENDPOINTS_0=http://elasticsearch:9200
  
  management_ui:
    image: graviteeio/management-ui:1.21.3
    volumes:
      - ./logs/management-ui:/var/log/httpd
    environment:
      - MGMT_API_URL=https://5gcity-dashboard.i2cat.net/management/api/management/
    links:
      - "management_api:management_api"

  # --------------------
  # Keycloak Services
  # --------------------

  keycloak:
    hostname: keycloak
    image: jboss/keycloak
    depends_on:
      - postgresdb
    links:
      - "postgresdb:postgresql"
    volumes:
      - ../keycloak/themes/5gcity-theme/:/opt/jboss/keycloak/themes/5gcity/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgresql
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_PORT=5432
      - ROOT_LOGLEVEL=INFO
      - AAA_AUTH_BASE_URL=http://localhost:8080/auth
      - PROXY_ADDRESS_FORWARDING=true
    extra_hosts:
      - "5gcity-dashboard.i2cat.net:192.168.111.234"

