version: '2'

volumes:
  mongo_data: {}
  elastic_data: {}
  postgres_data: {}

services:

  dashboard:
    build:
      context: DASH_PATH
      args:
        - API_BASE_URL=http://SERVER_NAME/gw/slicemanagerapi
        - AUTH_SERVER_URL=http://SERVER_NAME/auth
    volumes:
      - DASH_PATH/public/keycloak.json:/www/keycloak.json

  # --------------------
  # Auxiliary Services
  # --------------------
  nginx-service:
    image: nginx
    restart: always
    volumes:
    ports:
      - 80:80

  postgresdb:
    hostname: postgresql
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    hostname: aaaelasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536

  mongodb:
    hostname: aaamongodb
    image: mongo:3.4
    volumes:
      - mongo_data:/data/db

  # --------------------
  # GRAVITEE Services
  # --------------------

  gravitee_gateway:
    image: graviteeio/gateway:1.21.3
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/gateway:/etc/gravitee.io/log
      - ./scripts/gateway:/etc/gravitee.io/scripts
    environment:
      - GRAVITEE_HTTP_PORT=8000
      - GRAVITEE_MANAGEMENT_MONGODB_URI=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - GRAVITEE_REPORTERS_ELASTICSEARCH_ENDPOINTS_0=http://elasticsearch:9200

  management_api:
    image: graviteeio/management-api:1.21.3
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/management-api:/home/gravitee/logs
      - ./gravitee/api/gravitee.yml:/opt/graviteeio-management-api/config/gravitee.yml
    environment:
      - GRAVITEE_MANAGEMENT_MONGODB_URI=mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - GRAVITEE_ANALYTICS_ELASTICSEARCH_ENDPOINTS_0=http://elasticsearch:9200

  management_ui:
    image: graviteeio/management-ui:1.21.3
    volumes:
      - ./logs/management-ui:/var/log/httpd
    environment:
      - MGMT_API_URL=http://SERVER_NAME/management/api/management/
    links:
      - "management_api:management_api"

  # --------------------
  # Keycloak Services
  # --------------------

  keycloak:
    hostname: keycloak
    image: jboss/keycloak
    depends_on:
      - postgresdb
    links:
      - "postgresdb:postgresql"
    volumes:
      - ../keycloak/themes/5gcity-theme/:/opt/jboss/keycloak/themes/5gcity/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgresql
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_PORT=5432
      - ROOT_LOGLEVEL=INFO
      - PROXY_ADDRESS_FORWARDING=true
