version: '2'

volumes:
  mongo_data: {}
  elastic_data: {}
  postgres_data: {}

services:

  # --------------------
  # Auxiliary Services
  # --------------------


  postgresdb:
    hostname: postgresql
    image: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    network_mode: host
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536

  mongodb:
    network_mode: host
    image: mongo:3.4
    volumes:
      - mongo_data:/data/db

  # --------------------
  # GRAVITEE Services
  # --------------------

  gravitee_gateway:
    image: graviteeio/gateway:latest
    network_mode: host
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/gateway:/etc/gravitee.io/log
      - ./scripts/gateway:/etc/gravitee.io/scripts
    environment:
      - GRAVITEE_HTTP_PORT=8000
      - GRAVITEE_MANAGEMENT_MONGODB_URI=mongodb://0.0.0.0:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - GRAVITEE_REPORTERS_ELASTICSEARCH_ENDPOINTS_0=http://0.0.0.0:9200

  management_api:
    network_mode: host
    image: graviteeio/management-api:latest
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - ./logs/management-api:/home/gravitee/logs
    environment:
      - GRAVITEE_MANAGEMENT_MONGODB_URI=mongodb://0.0.0.0:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
      - GRAVITEE_ANALYTICS_ELASTICSEARCH_ENDPOINTS_0=http://0.0.0.0:9200

  management_ui:
    network_mode: host
    image: graviteeio/management-ui:latest
    volumes:
      - ./logs/management-ui:/var/log/httpd
    environment:
      - MGMT_API_URL=http:\/\/localhost:8083\/management\/

  # --------------------
  # Keycloak Services
  # --------------------

  keycloak:
    hostname: keycloak
    image: jboss/keycloak
    depends_on:
      - postgresdb
    links:
      - "postgresdb:postgresql"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgresql
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - ROOT_LOGLEVEL=INFO
    ports:
      - "8080:8080"